# Railway configuration for Oracle Service
[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.oracle.railway"

[deploy]
startCommand = "npx hardhat run scripts/oracle.ts --network somniaTestnet"
healthcheckPath = "/"
healthcheckTimeout = 30

[variables]
NODE_ENV = "production"
EVOLUTION_INTERVAL_MINUTES = "5"
MAX_TOKENS_PER_RUN = "10"
SINGLE_RUN = "false"
